version: "3.7"
services:
  hydra:
    image: oryd/hydra:v1.11.10
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
    command: serve all --dangerous-force-http
    environment:
      - SECRETS_SYSTEM=QoS0EOon13LyIEC1HDoM7SaX7QyiDoyz
      - URLS_SELF_ISSUER=https://localhost:5444/
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - OAUTH2_CLIENT_CREDENTIALS_DEFAULT_GRANT_ALLOWED_SCOPE=true
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - hydranet
  hydra-migrate:
    image: oryd/hydra:v1.11.10
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate sql -e --yes
    restart: on-failure
    networks:
      - hydranet
  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    networks:
      - hydranet
networks:
  hydranet:
